/*
 *****************************************************************************
 * Copyright @ 2009 by austriamicrosystems AG                                *
 * All rights are reserved.                                                  *
 *                                                                           *
 * Reproduction in whole or in part is prohibited without the written consent*
 * of the copyright owner. Austriamicrosystems reserves the right to make    *
 * changes without notice at any time. The software is provided as is and    *
 * Austriamicrosystems makes no warranty, expressed, implied or statutory,   *
 * including but not limited to any implied warranty of merchantability or   *
 * fitness for any particular purpose, or that the use will not infringe any *
 * third party patent, copyright or trademark. Austriamicrosystems should    *
 * not be liable for any loss or damage arising from its use.                *
 *****************************************************************************
 */
 
/*
 * PROJECT: AS3911 firmware
 * $Revision: $
 * LANGUAGE: ANSI C
 */
 
/*! \file as3911_irq.h
 *
 * \author Oliver Regenfelder
 *
 * \brief Handling of the external interrupt generated by the AS3911 in the PIC.
 *
 * Mandatory detailed description of the file
 */

#ifndef AS3911_IRQ_H
#define AS3911_IRQ_H
#include "stm32f10x_lib.h"
/*
******************************************************************************
* INCLUDES
******************************************************************************
*/

//#include <p24FJ64GB002.h>

/*
******************************************************************************
* DEFINES
******************************************************************************
*/

/*
******************************************************************************
* GLOBAL MACROS
******************************************************************************
*/

#define AS3911_EINT_LINE EXTI_Line1
//#define AS3911_IRQ_SOURCETYPE GPIO_PortSourceGPIOC
#define AS3911_IRQ_SOURCETYPE GPIO_PortSourceGPIOA //sxl
//#define AS3911_IRQ_SOURCENUM GPIO_PinSource6
#define AS3911_IRQ_SOURCENUM GPIO_PinSource1 //sxl

extern void EXTI_EnableITBit(u32 EXTI_Line);
extern void EXTI_DisableITBit(u32 EXTI_Line);

#define AS3911_IRQ_ON()  EXTI_EnableITBit(AS3911_EINT_LINE)
#define AS3911_IRQ_OFF() EXTI_DisableITBit(AS3911_EINT_LINE)
#define AS3911_IRQ_CLR() EXTI_ClearITPendingBit(AS3911_EINT_LINE)
#define AS3911_IRQ_IS_SET() EXTI_GetFlagStatus(AS3911_EINT_LINE)

/*
******************************************************************************
* GLOBAL DATA TYPES
******************************************************************************
*/

/*
******************************************************************************
* GLOBAL VARIABLE DECLARATIONS
******************************************************************************
*/

/*
******************************************************************************
* GLOBAL FUNCTION PROTOTYPES
******************************************************************************
*/

#endif /* AS3911_IRQ_H_ */
